server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yj_vivo50
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

    druid:
      aop-patterns: com.yj.boot.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat(sql监控)，wall(防火墙)

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false # 禁用重置

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*' # 排除静态资源

      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000 # 慢查询时长的判断依据
          logSlowSql: true
          enabled: true
        wall: # 防火墙
          enabled: true
          config:
            drop-table-allow: false # 禁止删表操作

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


# mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 日志
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      # 注意包路径分割符是点，直接在IDEA中copy的路径是斜杠会导致配置不生效
      packages-to-scan: com.xiaominfo.knife4j.demo.web

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

#oss:
#  bucket: test